import prod1 from "./images/prod1.png";
import prod2 from "./images/prod2.png";
import prod3 from "./images/prod3.png";
import prod4 from "./images/prod4.png";

export const story = [
  {
    id: 1,
    image: prod1,
    Name: "Tea",
    itemName: "The Weight Loss",
    itemNum: "Green Tea",
    ratings: 4,
    copyright: "By",
    manufacturer: "Phezy Food",
    price: 28,
    discount: 32,
    bar: " ",
    itemLeft: "Sold 60/100",
    buttonIcon: " ",
    buttonText: "Add To Cart",
  },
  {
    id: 2,
    image: prod2,
    Name: "Snack",
    itemName: "Seeds of Orange Organic",
    itemNum: "Quinoa, Brown, & Red Rice",
    ratings: 2,
    copyright: "By",
    manufacturer: "Phezy Food",
    price: 25,
    discount: 28,
    bar: " ",
    itemLeft: "Sold 40/100",
    buttonIcon: " ",
    buttonText: "Add To Cart",
  },
  {
    id: 3,
    image: prod3,
    Name: "Happilo",
    itemName: "Deluxe Walnut Kernels",
    itemNum: "100% Natural Kashmiri ",
    ratings: 3,
    copyright: "By",
    manufacturer: "Phezy Food",
    price: 39,
    discount: 45,
    bar: " ",
    itemLeft: "Sold 20/100",
    buttonIcon: " ",
    buttonText: "Add To Cart",
  },
  {
    id: 4,
    image: prod4,
    Name: "Snack",
    itemName: "Seeds of Orange Organic",
    itemNum: "Quinoa, Brown, & Red Rice",
    ratings: 5,
    copyright: "By",
    manufacturer: "Phezy Food",
    price: 10,
    discount: 12,
    bar: " ",
    itemLeft: "Sold 80/100",
    buttonIcon: " ",
    buttonText: "Add To Cart",
  },
];
